tagalog_expected_labels = ['higit sa 7',
                           'wala pang 3 beses',
                           '2 - 4 araw nakalipas',
                           'pagkaing dagat',
                           'dalawa',
                           'pangangati',
                           'malambot',
                           '3  - 5 beses',
                           'paggamot ng root canal',
                           'usok/alikabok',
                           'brownish',
                           'pasta/spaghetti',
                           '4 - 6 beses',
                           'wala pang 1 linggo',
                           '2 - 4 araw lumipas',
                           '38.3 - 38.6',
                           'dalawa kada linggo',
                           'near-sighted',
                           'pre existing condition',
                           'itim',
                           'loob',
                           'ubo',
                           'wala pang 1 araw',
                           'isa kada linggo',
                           '38',
                           'dalawa kada araw',
                           'medication',
                           '1 - 3 araw',
                           'aso',
                           'pusa',
                           '11 hanggang 20 minuto',
                           '3',
                           '7 - 10 na araw',
                           '0',
                           'medyo',
                           'higit 1 linggong nakalipas',
                           'tuyo',
                           'neozep',
                           '8 - 10 na araw',
                           'foreign object',
                           'dahil sa mga fluids',
                           'higit sa 10 minuto',
                           'avulsion',
                           'asul',
                           'puncture',
                           'exposure sa chlorine',
                           'kanina/ngayon lang',
                           '5 - 7 araw lumipas',
                           'tulog',
                           'lima',
                           'nadulas/nahulog',
                           'tinapay/pandesal',
                           'pula',
                           '9',
                           '7 pataas',
                           '4-6 araw',
                           'may dugo',
                           '1 - 3',
                           'pisikal na ehersisyo',
                           'wala pa isang linggo',
                           'higit sa 5 beses',
                           'hindi kailanman',
                           'buwan',
                           '5 - 7 na araw lumipas',
                           '8 pataas',
                           'ilang araw lang',
                           '1',
                           'higit sa 1 buwan',
                           'higit sa 20 minuto',
                           '5 - 7 na araw',
                           'maputla',
                           '4 to 7',
                           'pareho',
                           'aspirin',
                           'pamamantal',
                           'pito',
                           'wala pang 1 buwan',
                           'pag-bunot ng ngipin',
                           'wala pa isang minuto',
                           'mga oras lang',
                           'dilaw',
                           'di ko alam',
                           'bioflu',
                           'skin irritants',
                           'hindi',
                           '5',
                           'band-aid',
                           'food intake',
                           '7',
                           'sunburn',
                           '1 - 2 linggo',
                           'kulay-rosas/pula',
                           'gulay',
                           'ibang dahilan',
                           'matingkad na pula',
                           '5 - 7 araw nakalipas',
                           'labis na ehersisyo',
                           'higit sa 5 oras',
                           '37.9 - 38.2',
                           'ngayong araw',
                           'mani',
                           'higit sa 39',
                           'di higit sa isang araw',
                           'matubig',
                           'pagbahing',
                           'wala akong maalala',
                           'puti',
                           'antibiotics',
                           'wala pa isang buwan',
                           'kayumanggi/dark red',
                           'isa',
                           'merong plema',
                           '1 o higit pang buwan',
                           'nalimutan ko',
                           'pahinga',
                           'mga allergies',
                           'laceration',
                           'dahil sa pagkain',
                           'gatas',
                           'wala naman pong iba',
                           '6',
                           '1 - 5 minuto',
                           '1 hanggang 10 minuto',
                           'oras',
                           'human fault',
                           'kaliwa at kanan',
                           'no choices (free response)',
                           'tubig',
                           'yellowish',
                           '5 araw - 1 linggo',
                           '2 - 3 araw',
                           'hindi ko maalala o alam',
                           'wala pa isang oras',
                           'itlog',
                           'mahigit isang buwan',
                           '37.5 - 37.8',
                           'linggong nakalipas',
                           'apat',
                           'oo',
                           'kaagad-agad',
                           'dysmenorrhea',
                           '2 - 3 beses',
                           'mga segundo lang',
                           'sa panig ng ina',
                           '2',
                           'pasta',
                           'hindi ko nabilang',
                           'nakaraang linggo',
                           'oras na nalipas',
                           'trauma/injury',
                           'mga minuto lang',
                           'dehydration',
                           'tatlo',
                           'dahil sa trauma',
                           'isa kada araw',
                           '1 - 3 na araw',
                           'lagpas sa isang linggo',
                           'kulay rosas',
                           'kulay abo',
                           'ilang oras lang',
                           'manok, baboy o baka',
                           'nakaraaang buwan',
                           'dibdib',
                           'kamay/braso',
                           'wala',
                           'mga ilang araw',
                           'far-sighted',
                           'meron pa po pero okay naman po ako',
                           'nakalmot ang mata',
                           '1 - 3 beses',
                           'nakaraang buwan',
                           'mga painkiller na gamot',
                           'gamot 1',
                           'paa',
                           'kaliwa',
                           'higit sa 10 araw',
                           '39',
                           'hindi ko maalala',
                           'higit sa 6 na beses',
                           'higit sa 2 linggo',
                           'kape/tsaa',
                           'anim',
                           'baka',
                           'higit sa 24 oras',
                           'sa harapan',
                           'nakaraang taon',
                           'agad-agad',
                           'linggo',
                           'pagduduwal at pagsusuka',
                           'higit sa 1 linggo',
                           'ilang minuto lang',
                           '4 - 6',
                           'buo',
                           'bloody',
                           '1 - 5 na oras',
                           'hindi sigurado',
                           'pamumula',
                           'iba pa',
                           'mga prutas',
                           'higit sa isang linggo',
                           '4',
                           'wala pa isang araw',
                           'atis',
                           'tatlo kada araw',
                           'mukha',
                           '1 - 30 na minuto',
                           'hindi ko alam',
                           'nabangga ng sasakyan',
                           '4 - 6 na araw',
                           'dahon ng sambong',
                           '1 to 3',
                           'dahil sa gamot',
                           'hirap sa paghinga',
                           'higit dalawa kada linggo',
                           'matulis',
                           'pre-existing na kondisyon',
                           'abrasion',
                           'kulay kahel',
                           '2 - 4 na araw lumipas',
                           '1-3 araw',
                           'sabaw',
                           '2 - 4 na araw',
                           '31 - 60 na minuto',
                           'iba pang interbensyon',
                           'karahasan',
                           'taong nalipas',
                           'ibang kulay',
                           'ice cream/yogurt',
                           'lagnat',
                           'pamahid',
                           'kape',
                           'labas',
                           'softdrinks',
                           'wala pang 1 minuto',
                           '8',
                           'berde',
                           'kalamansi',
                           'sa panig ng ama',
                           'buwan na nakalipas',
                           'wala pang isang minuto',
                           'mabilog',
                           'sa kanan',
                           '5 araw -1 linggo',
                           'hight sa 10 araw',
                           'mas mababa',
                           'blister forming',
                           '10',
                           'higit pa o katumbas doon',
                           'mahigit 7 araw',
                           'higit dalawang araw',
                           'direct sunlight',
                           'sa likuran',
                           'kanan',
                           'kayumanggi',
                           'pagod',
                           'minutong nakalipas',
                           '1 linggong nakalipas',
                           'minsan',
                           '6 - 10 minuto',
                           'oras na nakalipas',
                           '40',
                           'orange',
                           'pamamaga',
                           'maitim',
                           'tumutulong sipon',
                           '38.7 - 39',
                           'kulay-ube',
                           'mga ilang oras lang',
                           'lumayo sa mga allergens',
                           'sakit sa ulo',
                           'anti histamine',
                           'palagi',
                           'meron',
                           'kahapon',
                           'sa kaliwa',
                           'ngayon / kanina lang']
