tagalog_labels = ['higit sa pito',
 'wala pang tatlo beses',
 'dalawa hanggang apat araw nakalipas',
 'pagkaing dagat',
 'dalawa',
 'pangangati',
 'malambot',
 'tatlo  - lima beses',
 'paggamot ng root canal',
 'usok/alikabok',
 'brownish',
 'pasta/spaghetti',
 'apat hanggang anim beses',
 'wala pang isa linggo',
 'dalawa hanggang apat araw lumipas',
 'thirty-eight point three to thirty-eight point six',
 'dalawa kada linggo',
 'near-sighted',
 'pre existing condition',
 'itim',
 'loob',
 'ubo',
 'wala pang isa araw',
 'isa kada linggo',
 'tatlumput siyam',
 'dalawa kada araw',
 'medication',
 'isa hanggang tatlo araw',
 'aso',
 'pusa',
 'labing-isa hanggang dalawampu minuto',
 'tatlo',
 'pito - sampu na araw',
 'zero',
 'medyo',
 'higit isa linggong nakalipas',
 'tuyo',
 'neozep',
 'walo - sampu na araw',
 'foreign object',
 'dahil sa mga fluids',
 'higit sa sampu minuto',
 'avulsion',
 'asul',
 'puncture',
 'exposure sa chlorine',
 'kanina/ngayon lang',
 'lima - pito araw lumipas',
 'tulog',
 'lima',
 'nadulas/nahulog',
 'tinapay/pandesal',
 'pula',
 'syam',
 'pito pataas',
 'apat-anim araw',
 'may dugo',
 'isa hanggang tatlo',
 'pisikal na ehersisyo',
 'wala pa isang linggo',
 'higit sa lima beses',
 'hindi kailanman',
 'buwan',
 'lima - pito na araw lumipas',
 'walo pataas',
 'ilang araw lang',
 'isa',
 'higit sa isa buwan',
 'higit sa dalawampu minuto',
 'lima - pito na araw',
 'maputla',
 'apat to pito',
 'pareho',
 'aspirin',
 'pamamantal',
 'pito',
 'wala pang isa buwan',
 'pag-bunot ng ngipin',
 'wala pa isang minuto',
 'mga oras lang',
 'dilaw',
 'di ko alam',
 'bioflu',
 'skin irritants',
 'hindi',
 'lima',
 'band-aid',
 'food intake',
 'pito',
 'sunburn',
 'isa - dalawa linggo',
 'kulay-rosas/pula',
 'gulay',
 'ibang dahilan',
 'matingkad na pula',
 'lima - pito araw nakalipas',
 'labis na ehersisyo',
 'higit sa lima oras',
 'thirty-seven point nine to thirty-eight point two',
 'ngayong araw',
 'mani',
 'higit sa tatlumput siyam',
 'di higit sa isang araw',
 'matubig',
 'pagbahing',
 'wala akong maalala',
 'puti',
 'antibiotics',
 'wala pa isang buwan',
 'kayumanggi/dark red',
 'isa',
 'merong plema',
 'isa o higit pang buwan',
 'nalimutan ko',
 'pahinga',
 'mga allergies',
 'laceration',
 'dahil sa pagkain',
 'gatas',
 'wala naman pong iba',
 'anim',
 'isa hanggang lima minuto',
 'isa hanggang sampu minuto',
 'oras',
 'human fault',
 'kaliwa at kanan',
 'no choices (free response)',
 'tubig',
 'yellowish',
 'lima araw - isa linggo',
 'dalawa - tatlo araw',
 'hindi ko maalala o alam',
 'wala pa isang oras',
 'itlog',
 'mahigit isang buwan',
 'thirty-seven point five to thirty-seven point eight',
 'linggong nakalipas',
 'apat',
 'oo',
 'kaagad-agad',
 'dysmenorrhea',
 'dalawa - tatlo beses',
 'mga segundo lang',
 'sa panig ng ina',
 'dalawa',
 'pasta',
 'hindi ko nabilang',
 'nakaraang linggo',
 'oras na nalipas',
 'trauma/injury',
 'mga minuto lang',
 'dehydration',
 'tatlo',
 'dahil sa trauma',
 'isa kada araw',
 'isa hanggang tatlo na araw',
 'lagpas sa isang linggo',
 'kulay rosas',
 'kulay abo',
 'ilang oras lang',
 'manok, baboy o baka',
 'nakaraaang buwan',
 'dibdib',
 'kamay/braso',
 'wala',
 'mga ilang araw',
 'far-sighted',
 'meron pa po pero okay naman po ako',
 'nakalmot ang mata',
 'isa hanggang tatlo beses',
 'nakaraang buwan',
 'mga painkiller na gamot',
 'gamot isa',
 'paa',
 'kaliwa',
 'higit sa sampu araw',
 'tatlumput siyam',
 'hindi ko maalala',
 'higit sa anim na beses',
 'higit sa dalawa linggo',
 'kape/tsaa',
 'anim',
 'baka',
 'higit sa dalawamput apat oras',
 'sa harapan',
 'nakaraang taon',
 'agad-agad',
 'linggo',
 'pagduduwal at pagsusuka',
 'higit sa isa linggo',
 'ilang minuto lang',
 'apat hanggang anim',
 'buo',
 'bloody',
 'isa hanggang lima na oras',
 'hindi sigurado',
 'pamumula',
 'iba pa',
 'mga prutas',
 'higit sa isang linggo',
 'apat',
 'wala pa isang araw',
 'atis',
 'tatlo kada araw',
 'mukha',
 'isa hanggang tatlumpung minuto na minuto',
 'hindi ko alam',
 'nabangga ng sasakyan',
 'apat hanggang anim na araw',
 'dahon ng sambong',
 'isa to tatlo',
 'dahil sa gamot',
 'hirap sa paghinga',
 'higit dalawa kada linggo',
 'matulis',
 'pre-existing na kondisyon',
 'abrasion',
 'kulay kahel',
 'dalawa hanggang apat na araw lumipas',
 'isa-tatlo araw',
 'sabaw',
 'dalawa hanggang apat na araw',
 'thirty one to sixty na minuto',
 'iba pang interbensyon',
 'karahasan',
 'taong nalipas',
 'ibang kulay',
 'ice cream/yogurt',
 'lagnat',
 'pamahid',
 'kape',
 'labas',
 'softdrinks',
 'wala pang isa minuto',
 'walo',
 'berde',
 'kalamansi',
 'sa panig ng ama',
 'buwan na nakalipas',
 'wala pang isang minuto',
 'mabilog',
 'sa kanan',
 'lima araw -isa linggo',
 'hight sa sampu araw',
 'mas mababa',
 'blister forming',
 'sampu',
 'higit pa o katumbas doon',
 'mahigit pito araw',
 'higit dalawang araw',
 'direct sunlight',
 'sa likuran',
 'kanan',
 'kayumanggi',
 'pagod',
 'minutong nakalipas',
 'isa linggong nakalipas',
 'minsan',
 'anim - sampu minuto',
 'oras na nakalipas',
 'apatnapu',
 'orange',
 'pamamaga',
 'maitim',
 'tumutulong sipon',
 'thirty-eight point seven to thirty-nine',
 'kulay-ube',
 'mga ilang oras lang',
 'lumayo sa mga allergens',
 'sakit sa ulo',
 'anti histamine',
 'palagi',
 'meron',
 'kahapon',
 'sa kaliwa',
 'ngayon / kanina lang']